# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options



class TestSmoketestsuite():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1Verifythatthelogoheadingandbrowsertitletabaredisplayed(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".header-logo img")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
    self.driver.set_window_size(1920, 1004)
  
  def test_2VerifythattheSpotlightandJoinUsLinkworksasexpected(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1920, 1004)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 > .centered-image")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 > .centered-image")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Join")))
    assert self.driver.find_element(By.LINK_TEXT, "Join").text == "Join"
  
  def test_3Verifydirectorypage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1920, 1004)
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Directory"))).click()
    self.driver.find_element(By.ID, "directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
    self.driver.find_element(By.ID, "directory-list").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
    self.driver.find_element(By.ID, "directory-grid").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
  
  def test_4Verifyjoinpage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1920, 1004)
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Join"))).click()
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".myinput:nth-child(2)").text == "First Name"
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("jordan")
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").send_keys("larcher")
    self.driver.find_element(By.NAME, "bizname").send_keys("test teton Idaho")
    self.driver.find_element(By.NAME, "biztitle").send_keys("QA")
    self.driver.find_element(By.NAME, "submit").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".myinput:nth-child(2)")
    assert len(elements) > 0
    # Wait for JavaScript to load and execute
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.NAME, "email")))
    value = self.driver.find_element(By.NAME, "email").get_attribute("value")
    # Email field should be empty initially (no default value expected)
    assert value == ""
    assert self.driver.find_element(By.CSS_SELECTOR, ".myinput:nth-child(2)").text == "Email"
    self.driver.set_window_size(1920, 1004)
  
  def test_5VerifyAdminpage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1920, 1004)
    self.driver.find_element(By.LINK_TEXT, "Admin").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("continue")
    self.driver.find_element(By.ID, "password").send_keys("testing")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".errorMessage")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
  
